### ISSUE TITLE
Window (default)

### ISSUE THREAD

**Issue by ModeAxe** [adicu/DevFest-2023#6]
This window contains the site's hero message. 
Window is draggable only in desktop view
Windows is open when site loads
Window can be closed only in desktop view
"DevFest 23" Icon opens window
See (https://www.figma.com/file/GEu7MTYyOOwK6ivSoPVyak/DevFest-23---Website?node-id=0%3A1&t=VREGB5LEWjxdUY3F-1)

**Comment by ethmth** [comment]
@ModeAxe @ellenguo6 I just requested access to the Figma if I could be approved for that.

**Comment by ellenguo6** [comment]
closed by #8
